pipelines:
  mypipe1: # definition of mypipe1 pipeline
    group: mygroup # note that the group name can contain only of alphanumeric & underscore characters
    label_template: "${mygit[:8]}"
    lock_behavior: none
    parameters: # list of parameters that can be configured for a pipeline
      param1: value1
    materials:
      mygit: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: https://github.com/radudragulin/GoCD.git
        branch: master
    stages:
     - build:
         clean_workspace: true
         jobs: 
           maven:
             tasks:
              - exec: # indicates type of task
                  command: make
                  arguments:
                   - "VERBOSE=true"
          
